### ISSUE TITLE
post json 怎么写？

### ISSUE THREAD

**Issue by yuanzhihai** [gouguoyin/easyhttp#4]
GuzzleHttp 是这么写的
```
 $response = $client->request(
            'post',
            $url,
            [
                'json' => [
                   
                ],
            ]
        );
  ```      
       下面写不行
```
 Http::asJson()->post($url,$postArr)->toArray(); 
```
 应该怎么写？

**Comment by gouguoyin** [comment]
Http::asJson()-&gt;post($url,$postArr)-&gt;toArray();这样写是对的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月14日(周六) 晚上9:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gouguoyin/easyhttp] post json 怎么写？ (#4)




 
GuzzleHttp 是这么写的
 $response = $client-&gt;request(
 'post',
 $url,
 [
 'json' =&gt; [
             ],         ]     );          这个扩展 这么写不可以？  
Http::asJson()-&gt;post($url,$postArr)-&gt;toArray();
 应该怎么写？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yzh52521** [comment]
> Http::asJson()-&gt;post($url,$postArr)-&gt;toArray();这样写是对的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月14日(周六) 晚上9:53 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [gouguoyin/easyhttp] post json 怎么写？ (#4) GuzzleHttp 是这么写的 $response = $client-&gt;request( 'post', $url, [ 'json' =&gt; [ ], ] ); 这个扩展 这么写不可以？ Http::asJson()-&gt;post($url,$postArr)-&gt;toArray(); 应该怎么写？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

不行的 我试过了 要不也不请教你

**Comment by gouguoyin** [comment]
这个还有问题么？
